<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6dMKTx9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6dMKTx9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6dMKTx9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6dMKTx9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6dMKTx9\App_KernelDevDebugContainer([
    'container.build_hash' => '6dMKTx9',
    'container.build_id' => '4d5b89ea',
    'container.build_time' => 1611936481,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6dMKTx9');
