<?php

namespace Container6dMKTx9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookListControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\BookListController' shared service.
     *
     * @return \App\Controller\BookListController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/BookListController.php';
        include_once \dirname(__DIR__, 4).'/src/Repository/BookRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Environment.php';
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Loader/LoaderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Loader/FilesystemLoader.php';

        return $container->services['App\\Controller\\BookListController'] = new \App\Controller\BookListController(new \App\Repository\BookRepository(), new \Twig\Environment(new \Twig\Loader\FilesystemLoader((\dirname(__DIR__, 4).'/templates'))));
    }
}
